CAMERA_INDEX = 0

MAX_NUM_HANDS = 1
MIN_DETECTION_CONFIDENCE = 0.7
MIN_TRACKING_CONFIDENCE = 0.7

COOLDOWN_SECONDS = 1.5
GESTURE_BUFFER_SIZE = 5

WINDOW_NAME = "Gesture Control v3"

VALID_GESTURES = ["OPEN_PALM", "FIST", "PEACE"]

TEXT_POS_GESTURE = (10, 35)
TEXT_POS_ACTION = (10, 75)
TEXT_POS_HINT = (10, 115)
TEXT_POS_MODE = (10, 155)

FONT_SCALE_GESTURE = 1
FONT_SCALE_ACTION = 0.8
FONT_SCALE_HINT = 0.7
FONT_SCALE_MODE = 0.8

THICKNESS_GESTURE = 2
THICKNESS_ACTION = 2
THICKNESS_HINT = 2
THICKNESS_MODE = 2

COLOR_GREEN = (0, 255, 0)
COLOR_RED = (0, 0, 255)
COLOR_YELLOW = (255, 255, 0)
COLOR_GRAY = (200, 200, 200)
COLOR_CYAN = (255, 255, 0)

MOUSE_SMOOTHING = 0.2
MOUSE_CLICK_THRESHOLD = 0.04

PINCH_DRAG_HOLD_TIME = 0.35
PINCH_RELEASE_GRACE_TIME = 0.12
MOUSE_PINCH_SMOOTHING = 0.12

MODE_GESTURE = "GESTURE"
MODE_MOUSE = "MOUSE"
DEFAULT_MODE = MODE_GESTURE

GESTURE_HOLD_TIME = 1.2  # seconds

INVERT_X = False
INVERT_Y = False

MOUSE_CLICK_THRESHOLD = 0.04
MOUSE_SMOOTHING = 0.25
MOUSE_GAIN_X = 1.4
MOUSE_GAIN_Y = 1.4

CONTROL_REGION_MIN_X = 0.20
CONTROL_REGION_MAX_X = 0.80
CONTROL_REGION_MIN_Y = 0.20
CONTROL_REGION_MAX_Y = 0.80

SHOW_CONTROL_REGION = True

AUTO_SWITCH_TO_GESTURE_ON_OUTSIDE = True
OUTSIDE_BOX_TIMEOUT = 2.0
